// Component Registry - Central hub for all Tailwind UI Plus components
// This makes it easy for AI to discover and reference components

export interface ComponentInfo {
  id: string;
  name: string;
  description: string;
  category: string;
  subcategory?: string;
  tags: string[];
  complexity: 'simple' | 'medium' | 'complex';
  responsive: boolean;
  darkMode: boolean;
  filePath: string;
  previewImage?: string;
  dependencies?: string[];
}

export interface ComponentCategory {
  id: string;
  name: string;
  description: string;
  icon: string;
  subcategories?: ComponentSubcategory[];
}

export interface ComponentSubcategory {
  id: string;
  name: string;
  description: string;
  count: number;
}

// Main Categories from Tailwind UI Plus
export const COMPONENT_CATEGORIES: ComponentCategory[] = [
  {
    id: 'page-sections',
    name: 'Page Sections',
    description: 'Complete page sections ready to use',
    icon: '📄',
    subcategories: [
      { id: 'hero-sections', name: 'Hero Sections', description: 'Landing page heroes', count: 0 },
      { id: 'feature-sections', name: 'Feature Sections', description: 'Product feature showcases', count: 14 },
      { id: 'cta-sections', name: 'CTA Sections', description: 'Call-to-action sections', count: 11 },
      { id: 'bento-grids', name: 'Bento Grids', description: 'Modern grid layouts', count: 3 },
      { id: 'pricing-sections', name: 'Pricing Sections', description: 'Pricing tables and plans', count: 13 },
      { id: 'header-sections', name: 'Header Sections', description: 'Page headers and navigation', count: 8 },
      { id: 'newsletter-sections', name: 'Newsletter Sections', description: 'Email signup sections', count: 6 },
      { id: 'stats', name: 'Stats', description: 'Statistics and metrics', count: 8 },
      { id: 'testimonials', name: 'Testimonials', description: 'Customer testimonials', count: 8 },
      { id: 'blog-sections', name: 'Blog Sections', description: 'Blog and content sections', count: 7 },
      { id: 'contact-sections', name: 'Contact Sections', description: 'Contact forms and info', count: 7 },
      { id: 'team-sections', name: 'Team Sections', description: 'Team member showcases', count: 9 },
      { id: 'content-sections', name: 'Content Sections', description: 'General content layouts', count: 7 },
      { id: 'logo-clouds', name: 'Logo Clouds', description: 'Company logo collections', count: 6 },
      { id: 'faqs', name: 'FAQs', description: 'Frequently asked questions', count: 7 },
      { id: 'footers', name: 'Footers', description: 'Page footers', count: 8 }
    ]
  },
  {
    id: 'elements',
    name: 'Elements',
    description: 'Individual UI elements and components',
    icon: '🧩',
    subcategories: [
      { id: 'headers', name: 'Headers', description: 'Navigation headers', count: 11 },
      { id: 'flyout-menus', name: 'Flyout Menus', description: 'Dropdown and flyout menus', count: 7 },
      { id: 'banners', name: 'Banners', description: 'Notification banners', count: 14 },
      { id: 'feedback', name: 'Feedback', description: 'User feedback components', count: 0 },
      { id: '404-pages', name: '404 Pages', description: 'Error page layouts', count: 0 }
    ]
  },
  {
    id: 'page-examples',
    name: 'Page Examples',
    description: 'Complete page templates',
    icon: '📱',
    subcategories: [
      { id: 'landing-pages', name: 'Landing Pages', description: 'Complete landing page templates', count: 4 },
      { id: 'pricing-pages', name: 'Pricing Pages', description: 'Pricing page templates', count: 3 },
      { id: 'about-pages', name: 'About Pages', description: 'About page templates', count: 0 }
    ]
  },
  {
    id: 'application-ui',
    name: 'Application UI',
    description: 'App interface components',
    icon: '💻',
    subcategories: [
      { id: 'forms', name: 'Forms', description: 'Form components and layouts', count: 0 },
      { id: 'tables', name: 'Tables', description: 'Data tables and lists', count: 0 },
      { id: 'navigation', name: 'Navigation', description: 'App navigation components', count: 0 },
      { id: 'layout', name: 'Layout', description: 'App layout components', count: 0 },
      { id: 'overlays', name: 'Overlays', description: 'Modals and overlays', count: 0 },
      { id: 'lists', name: 'Lists', description: 'List components', count: 0 },
      { id: 'headings', name: 'Headings', description: 'Heading components', count: 0 },
      { id: 'cards', name: 'Cards', description: 'Card components', count: 0 }
    ]
  }
];

// Component Registry - This will hold all your components
export const COMPONENT_REGISTRY: ComponentInfo[] = [
  // Existing components
  {
    id: 'simple-hero',
    name: 'Simple Hero',
    description: 'Centered hero with gradient background and dual CTAs',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'landing', 'cta', 'gradient', 'centered'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/heroes/SimpleHero.tsx'
  },
  {
    id: 'split-hero',
    name: 'Split Hero',
    description: 'Two-column layout with text on left, image on right',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'split', 'image', 'two-column'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/heroes/SplitHero.tsx'
  },
  {
    id: 'simple-pricing',
    name: 'Simple Pricing',
    description: 'Clean three-tier pricing with popular highlight',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'plans', 'subscription', 'three-tier'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/pricing/SimplePricing.tsx'
  },
  {
    id: 'navigation-hero',
    name: 'Navigation Hero',
    description: 'Hero with full navigation header and mobile menu',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'navigation', 'mobile-menu', 'landing', 'gradient', 'announcement'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/NavigationHero.tsx'
  },
  {
    id: 'product-hero',
    name: 'Product Hero',
    description: 'Split layout hero with product screenshot and logo',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'product', 'split-layout', 'image', 'logo', 'announcement'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/ProductHero.tsx'
  },
  {
    id: 'app-hero',
    name: 'App Hero',
    description: 'Application focused hero with bordered screenshot',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'app', 'split-layout', 'image', 'border', 'screenshot'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/AppHero.tsx'
  },
  {
    id: 'split-code-hero',
    name: 'Split Code Hero',
    description: 'Two-column hero with text and code example showcase',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'code', 'split-layout', 'developer', 'gradient', 'announcement'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/SplitCodeHero.tsx'
  },
  {
    id: 'background-image-hero',
    name: 'Background Image Hero',
    description: 'Centered hero with full-screen background image and navigation',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'background-image', 'navigation', 'mobile-menu', 'centered', 'announcement'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/BackgroundImageHero.tsx'
  },
  {
    id: 'bordered-screenshot-hero',
    name: 'Bordered Screenshot Hero',
    description: 'Centered hero with bordered app screenshot and navigation',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'screenshot', 'navigation', 'mobile-menu', 'centered', 'bordered'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/BorderedScreenshotHero.tsx'
  },
  {
    id: 'app-screenshot-hero',
    name: 'App Screenshot Hero',
    description: 'Centered hero with navigation and clean app screenshot display',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'app', 'screenshot', 'navigation', 'mobile-menu', 'centered'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/AppScreenshotHero.tsx'
  },
  {
    id: 'phone-mockup-hero',
    name: 'Phone Mockup Hero',
    description: 'Split layout hero with realistic phone mockup display',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'phone', 'mockup', 'mobile', 'navigation', 'announcement', 'split-layout'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/PhoneMockupHero.tsx'
  },
  {
    id: 'split-image-hero',
    name: 'Split Image Hero',
    description: 'Two-column layout with text content and full-height image',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'split-layout', 'image', 'two-column', 'announcement'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/SplitImageHero.tsx'
  },
  {
    id: 'angled-image-hero',
    name: 'Angled Image Hero',
    description: 'Split layout with angled SVG transition and full-height image',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'angled', 'split-layout', 'image', 'navigation', 'announcement'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/AngledImageHero.tsx'
  },
  {
    id: 'image-tiles-hero',
    name: 'Image Tiles Hero',
    description: 'Hero with staggered image tiles gallery display',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'images', 'tiles', 'gallery', 'navigation', 'staggered'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/ImageTilesHero.tsx'
  },
  {
    id: 'offset-image-hero',
    name: 'Offset Image Hero',
    description: 'Hero with offset positioned image and skewed background',
    category: 'page-sections',
    subcategory: 'hero-sections',
    tags: ['hero', 'offset', 'image', 'navigation', 'skewed', 'gradient'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/hero-sections/OffsetImageHero.tsx'
  },
  {
    id: 'product-screenshot-feature',
    name: 'Product Screenshot Feature',
    description: 'Two-column feature section with product screenshot and feature list',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'product', 'screenshot', 'two-column', 'icons', 'list'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/ProductScreenshotFeature.tsx'
  },
  {
    id: 'large-screenshot-feature',
    name: 'Large Screenshot Feature',
    description: 'Centered header with large screenshot and feature grid below',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'screenshot', 'large', 'grid', 'icons', 'centered'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/LargeScreenshotFeature.tsx'
  },
  {
    id: 'bordered-screenshot-feature',
    name: 'Bordered Screenshot Feature',
    description: 'Simple title with large bordered screenshot display',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'screenshot', 'bordered', 'simple', 'minimal'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/BorderedScreenshotFeature.tsx'
  },
  {
    id: 'simple-three-column-feature',
    name: 'Simple Three Column Feature',
    description: 'Three-column feature section with small icons and centered content',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'three-column', 'icons', 'centered', 'list', 'learn-more'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/SimpleThreeColumnFeature.tsx'
  },
  {
    id: 'screenshot-left-feature',
    name: 'Screenshot Left Feature',
    description: 'Two-column feature section with product screenshot on the left side',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'screenshot', 'two-column', 'product', 'icons', 'split-layout'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/ScreenshotLeftFeature.tsx'
  },
  {
    id: 'large-icons-feature',
    name: 'Large Icons Feature',
    description: 'Three-column feature section with large contained icons and simple layout',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'large-icons', 'three-column', 'simple', 'contained-icons', 'learn-more'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/LargeIconsFeature.tsx'
  },
  {
    id: 'contained-panel-feature',
    name: 'Contained Panel Feature',
    description: 'Dark panel with gradient background containing screenshot and feature list',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'panel', 'dark', 'gradient', 'screenshot', 'contained', 'two-column'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/ContainedPanelFeature.tsx'
  },
  {
    id: 'screenshot-panel-feature',
    name: 'Screenshot Panel Feature',
    description: 'Two-column layout with feature list and angled screenshot panel',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'screenshot', 'panel', 'angled', 'two-column', 'icons', 'skewed'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/ScreenshotPanelFeature.tsx'
  },
  {
    id: 'testimonial-feature',
    name: 'Testimonial Feature',
    description: 'Feature section with testimonial quote, CTA button, and product screenshot',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'testimonial', 'cta', 'screenshot', 'two-column', 'quote', 'avatar'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/TestimonialFeature.tsx'
  },
  {
    id: 'code-example-panel-feature',
    name: 'Code Example Panel Feature',
    description: 'Two-column layout with feature list and angled code example panel',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'code', 'panel', 'angled', 'two-column', 'syntax-highlighting', 'tabs'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/CodeExamplePanelFeature.tsx'
  },
  {
    id: 'offset-feature-list-feature',
    name: 'Offset Feature List Feature',
    description: 'Five-column grid with offset header and comprehensive feature list',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'offset', 'five-column', 'grid', 'checklist', 'comprehensive'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/OffsetFeatureListFeature.tsx'
  },
  {
    id: 'simple-feature-list-feature',
    name: 'Simple Feature List Feature',
    description: 'Clean three-column grid layout with feature titles and descriptions',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'simple', 'three-column', 'grid', 'minimal', 'clean'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/SimpleFeatureListFeature.tsx'
  },
  {
    id: 'centered-2x2-grid-feature',
    name: 'Centered 2x2 Grid Feature',
    description: 'Centered header with 2x2 grid layout featuring large contained icons',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'centered', '2x2', 'grid', 'large-icons', 'contained-icons'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/Centered2x2GridFeature.tsx'
  },
  {
    id: 'simple-3x2-grid-feature',
    name: 'Simple 3x2 Grid Feature',
    description: 'Left-aligned header with 3x2 grid layout featuring small inline icons',
    category: 'page-sections',
    subcategory: 'feature-sections',
    tags: ['features', 'simple', '3x2', 'grid', 'small-icons', 'inline', 'left-aligned'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/feature-sections/Simple3x2GridFeature.tsx'
  },
  {
    id: 'dark-panel-app-screenshot-cta',
    name: 'Dark Panel App Screenshot CTA',
    description: 'Dark panel with gradient background, app screenshot, and dual CTAs',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'dark-panel', 'gradient', 'app-screenshot', 'dual-cta', 'two-column'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/DarkPanelAppScreenshotCTA.tsx'
  },
  {
    id: 'simple-stacked-cta',
    name: 'Simple Stacked CTA',
    description: 'Minimal left-aligned title with stacked CTA buttons',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'simple', 'stacked', 'left-aligned', 'dual-cta', 'minimal'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/SimpleStackedCTA.tsx'
  },
  {
    id: 'centered-dark-panel-cta',
    name: 'Centered Dark Panel CTA',
    description: 'Centered content on dark panel with gradient background and dual CTAs',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'centered', 'dark-panel', 'gradient', 'dual-cta'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/CenteredDarkPanelCTA.tsx'
  },
  {
    id: 'simple-centered-cta',
    name: 'Simple Centered CTA',
    description: 'Clean centered layout with title, subtitle, and dual CTAs',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'simple', 'centered', 'clean', 'dual-cta', 'minimal'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/SimpleCenteredCTA.tsx'
  },
  {
    id: 'simple-centered-gradient-cta',
    name: 'Simple Centered Gradient CTA',
    description: 'Centered layout with subtle gradient background and dual CTAs',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'simple', 'centered', 'gradient', 'subtle', 'dual-cta'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/SimpleCenteredGradientCTA.tsx'
  },
  {
    id: 'simple-centered-on-brand-cta',
    name: 'Simple Centered On Brand CTA',
    description: 'Centered CTA on brand color background with white primary button',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'centered', 'brand-background', 'indigo', 'dual-cta'],
    complexity: 'simple',
    responsive: true,
    darkMode: false,
    filePath: 'src/components/ui/page-sections/cta-sections/SimpleCenteredOnBrandCTA.tsx'
  },
  {
    id: 'simple-justified-cta',
    name: 'Simple Justified CTA',
    description: 'Left-aligned title with right-aligned CTA buttons in justified layout',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'justified', 'left-aligned', 'right-aligned', 'dual-cta', 'layout'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/SimpleJustifiedCTA.tsx'
  },
  {
    id: 'simple-justified-on-subtle-brand-cta',
    name: 'Simple Justified On Subtle Brand CTA',
    description: 'Justified layout on subtle brand background with dual CTAs',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'justified', 'subtle-brand', 'indigo', 'dual-cta', 'background'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/SimpleJustifiedOnSubtleBrandCTA.tsx'
  },
  {
    id: 'split-with-image-cta',
    name: 'Split With Image CTA',
    description: 'Split layout with image background on left and content with CTA on right',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'split-layout', 'image', 'gradient', 'eyebrow', 'single-cta'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/SplitWithImageCTA.tsx'
  },
  {
    id: 'two-columns-with-photo-cta',
    name: 'Two Columns With Photo CTA',
    description: 'Two-column layout with photo, benefits checklist, and link CTA',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'two-column', 'photo', 'benefits', 'checklist', 'icons', 'gradient'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/TwoColumnsWithPhotoCTA.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'with-image-tiles-cta',
    name: 'With Image Tiles CTA',
    description: 'Complex layout with staggered image tiles gallery and content CTA',
    category: 'page-sections',
    subcategory: 'cta-sections',
    tags: ['cta', 'image-tiles', 'gallery', 'staggered', 'complex-layout', 'single-cta'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/cta-sections/WithImageTilesCTA.tsx'
  },
  {
    id: 'three-column-bento-grid',
    name: 'Three Column Bento Grid',
    description: 'Modern bento-style grid with three columns featuring mobile, performance, security, and API sections',
    category: 'page-sections',
    subcategory: 'bento-grids',
    tags: ['bento', 'grid', 'three-column', 'mobile', 'performance', 'security', 'apis', 'modern'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/bento-grids/ThreeColumnBentoGrid.tsx'
  },
  {
    id: 'two-row-bento-grid',
    name: 'Two Row Bento Grid',
    description: 'Two-row bento grid layout with releases, integrations, security, and performance sections',
    category: 'page-sections',
    subcategory: 'bento-grids',
    tags: ['bento', 'grid', 'two-row', 'releases', 'integrations', 'security', 'performance', '6-column'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/bento-grids/TwoRowBentoGrid.tsx'
  },
  {
    id: 'two-row-three-column-bento-grid',
    name: 'Two Row Three Column Bento Grid',
    description: 'Complex bento grid with two rows and three-column bottom section featuring performance, releases, speed, integrations, and network',
    category: 'page-sections',
    subcategory: 'bento-grids',
    tags: ['bento', 'grid', 'two-row', 'three-column', 'performance', 'releases', 'speed', 'integrations', 'network'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/bento-grids/TwoRowThreeColumnBentoGrid.tsx'
  },
  {
    id: 'two-tiers-emphasized-right-pricing',
    name: 'Two Tiers Emphasized Right Pricing',
    description: 'Two-tier pricing table with right tier emphasized in dark theme, featuring gradient background',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'two-tier', 'emphasized-right', 'dark', 'gradient', 'comparison'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/TwoTiersEmphasizedRightPricing.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'two-tiers-emphasized-left-pricing',
    name: 'Two Tiers Emphasized Left Pricing',
    description: 'Two-tier pricing table with left tier emphasized in light theme, featuring gradient background',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'two-tier', 'emphasized-left', 'light', 'gradient', 'comparison'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/TwoTiersEmphasizedLeftPricing.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'three-logos-feature-comparison-pricing',
    name: 'Three Logos Feature Comparison Pricing',
    description: 'Comprehensive three-tier pricing with company logos, detailed feature comparison table, and mobile tabs',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'three-tier', 'logos', 'feature-comparison', 'table', 'tabs', 'comprehensive', 'radial-gradient'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/ThreeLogosFeatureComparisonPricing.tsx',
    dependencies: ['@heroicons/react/16/solid', '@headlessui/react']
  },
  {
    id: 'two-tiers-with-extra-tier',
    name: 'Two Tiers With Extra Tier',
    description: 'Two main pricing tiers with additional discounted tier section below',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'two-tier', 'extra-tier', 'gradient', 'dark-hero', 'discount'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/TwoTiersWithExtraTier.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'single-price-with-details',
    name: 'Single Price With Details',
    description: 'Single lifetime membership pricing with detailed features list',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'single-price', 'lifetime', 'features-list', 'split-layout', 'simple'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/SinglePriceWithDetails.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'three-tiers-pricing',
    name: 'Three Tiers Pricing',
    description: 'Standard three-tier pricing with middle tier highlighted as "Most popular"',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'three-tier', 'most-popular', 'standard', 'highlighted', 'classic'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/ThreeTiersPricing.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'three-tiers-with-dividers',
    name: 'Three Tiers With Dividers',
    description: 'Three-tier pricing with visual dividers between columns and annual pricing display',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'three-tier', 'dividers', 'annual-pricing', 'clean', 'minimal'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/ThreeTiersWithDividers.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'three-tiers-with-emphasized-tier',
    name: 'Three Tiers With Emphasized Tier',
    description: 'Three-tier pricing with dark emphasized tier, frequency toggle, and form integration',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'three-tier', 'emphasized', 'frequency-toggle', 'form', 'interactive', 'dark-tier'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/ThreeTiersWithEmphasizedTier.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'three-tiers-with-toggle',
    name: 'Three Tiers With Toggle',
    description: 'Three-tier pricing with frequency toggle, "Most popular" badge, and ring emphasis',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'three-tier', 'toggle', 'most-popular', 'badge', 'ring-emphasis', 'interactive'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/ThreeTiersWithToggle.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'four-tiers-with-toggle',
    name: 'Four Tiers With Toggle',
    description: 'Four-tier pricing with frequency toggle, featured tier highlighting, and responsive grid layout',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'four-tier', 'toggle', 'featured', 'responsive', 'interactive'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/FourTiersWithToggle.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'with-comparison-table',
    name: 'With Comparison Table',
    description: 'Three-tier pricing with comprehensive feature comparison table, responsive mobile/desktop views',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'comparison-table', 'three-tier', 'responsive', 'table', 'comprehensive'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/WithComparisonTable.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'three-tiers-with-feature-comparison',
    name: 'Three Tiers With Feature Comparison',
    description: 'Advanced three-tier pricing with dark hero section, frequency toggle, and comprehensive feature comparison table',
    category: 'page-sections',
    subcategory: 'pricing-sections',
    tags: ['pricing', 'three-tier', 'feature-comparison', 'dark-hero', 'gradient', 'toggle', 'advanced'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/pricing-sections/ThreeTiersWithFeatureComparison.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'header-with-stats',
    name: 'Header With Stats',
    description: 'Header with background image, navigation links, and statistics grid',
    category: 'page-sections',
    subcategory: 'header-sections',
    tags: ['header', 'stats', 'background-image', 'gradient', 'links', 'careers'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/header-sections/HeaderWithStats.tsx'
  },
  {
    id: 'centered-header',
    name: 'Centered Header',
    description: 'Simple centered header with title and description',
    category: 'page-sections',
    subcategory: 'header-sections',
    tags: ['header', 'centered', 'simple', 'minimal', 'clean'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/header-sections/CenteredHeader.tsx'
  },
  {
    id: 'centered-with-eyebrow-header',
    name: 'Centered With Eyebrow Header',
    description: 'Centered header with eyebrow text, title, and description',
    category: 'page-sections',
    subcategory: 'header-sections',
    tags: ['header', 'centered', 'eyebrow', 'branded', 'support'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/header-sections/CenteredWithEyebrowHeader.tsx'
  },
  {
    id: 'header-with-cards',
    name: 'Header With Cards',
    description: 'Header with background effects and support category cards with icons',
    category: 'page-sections',
    subcategory: 'header-sections',
    tags: ['header', 'cards', 'icons', 'background-image', 'gradient', 'support'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/header-sections/HeaderWithCards.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'simple-header',
    name: 'Simple Header',
    description: 'Left-aligned basic header with title and description',
    category: 'page-sections',
    subcategory: 'header-sections',
    tags: ['header', 'left-aligned', 'simple', 'minimal', 'support'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/header-sections/SimpleHeader.tsx'
  },
  {
    id: 'simple-with-eyebrow-header',
    name: 'Simple With Eyebrow Header',
    description: 'Left-aligned header with eyebrow text, title, and description',
    category: 'page-sections',
    subcategory: 'header-sections',
    tags: ['header', 'left-aligned', 'eyebrow', 'branded', 'support'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/header-sections/SimpleWithEyebrowHeader.tsx'
  },
  {
    id: 'simple-with-background-image-header',
    name: 'Simple With Background Image Header',
    description: 'Left-aligned header with background image and gradient effects',
    category: 'page-sections',
    subcategory: 'header-sections',
    tags: ['header', 'left-aligned', 'background-image', 'gradient', 'support'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/header-sections/SimpleWithBackgroundImageHeader.tsx'
  },
  {
    id: 'centered-with-background-image-header',
    name: 'Centered With Background Image Header',
    description: 'Centered header with background image and gradient effects',
    category: 'page-sections',
    subcategory: 'header-sections',
    tags: ['header', 'centered', 'background-image', 'gradient', 'support'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/header-sections/CenteredWithBackgroundImageHeader.tsx'
  },
  {
    id: 'side-by-side-with-details',
    name: 'Side-by-side with Details',
    description: 'Newsletter signup with feature details and gradient background',
    category: 'page-sections',
    subcategory: 'newsletter-sections',
    tags: ['newsletter', 'side-by-side', 'features', 'icons', 'gradient'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/newsletter-sections/SideBySideWithDetails.tsx',
    dependencies: ['@heroicons/react/24/outline']
  },
  {
    id: 'simple-side-by-side',
    name: 'Simple Side-by-side',
    description: 'Clean side-by-side layout with privacy policy link',
    category: 'page-sections',
    subcategory: 'newsletter-sections',
    tags: ['newsletter', 'side-by-side', 'simple', 'privacy'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/newsletter-sections/SimpleSideBySide.tsx'
  },
  {
    id: 'simple-side-by-side-on-brand',
    name: 'Simple Side-by-side on Brand',
    description: 'Brand-colored background with white form elements',
    category: 'page-sections',
    subcategory: 'newsletter-sections',
    tags: ['newsletter', 'side-by-side', 'brand', 'indigo'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/newsletter-sections/SimpleSideBySideOnBrand.tsx'
  },
  {
    id: 'simple-stacked',
    name: 'Simple Stacked',
    description: 'Vertical layout with title above form',
    category: 'page-sections',
    subcategory: 'newsletter-sections',
    tags: ['newsletter', 'stacked', 'simple', 'vertical'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/newsletter-sections/SimpleStacked.tsx'
  },
  {
    id: 'centered-card',
    name: 'Centered Card',
    description: 'Dark card with gradient background and centered form',
    category: 'page-sections',
    subcategory: 'newsletter-sections',
    tags: ['newsletter', 'centered', 'card', 'dark', 'gradient'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/newsletter-sections/CenteredCard.tsx'
  },
  {
    id: 'side-by-side-on-card',
    name: 'Side-by-side on Card',
    description: 'Dark card with side-by-side layout and gradient background',
    category: 'page-sections',
    subcategory: 'newsletter-sections',
    tags: ['newsletter', 'side-by-side', 'card', 'dark', 'gradient'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/newsletter-sections/SideBySideOnCard.tsx'
  },
  {
    id: 'simple-stats',
    name: 'Simple',
    description: 'Clean centered layout with three key statistics',
    category: 'page-sections',
    subcategory: 'stats',
    tags: ['stats', 'centered', 'simple', 'clean'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/stats/Simple.tsx'
  },
  {
    id: 'simple-grid-stats',
    name: 'Simple Grid',
    description: 'Four statistics in a grid layout with background tiles',
    category: 'page-sections',
    subcategory: 'stats',
    tags: ['stats', 'grid', 'title', 'description'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/stats/SimpleGrid.tsx'
  },
  {
    id: 'with-background-image-stats',
    name: 'With Background Image',
    description: 'Statistics with background image and gradient overlay',
    category: 'page-sections',
    subcategory: 'stats',
    tags: ['stats', 'background-image', 'gradient', 'eyebrow'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/stats/WithBackgroundImage.tsx'
  },
  {
    id: 'split-with-image-stats',
    name: 'Split with Image',
    description: 'Half image, half content layout with statistics',
    category: 'page-sections',
    subcategory: 'stats',
    tags: ['stats', 'split', 'image', 'half-layout'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/stats/SplitWithImage.tsx'
  },
  {
    id: 'timeline-stats',
    name: 'Timeline',
    description: 'Company milestones displayed as a timeline with connecting lines',
    category: 'page-sections',
    subcategory: 'stats',
    tags: ['timeline', 'milestones', 'history', 'dates'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/stats/Timeline.tsx'
  },
  {
    id: 'stepped-stats',
    name: 'Stepped',
    description: 'Visual hierarchy with different colored cards and varying sizes',
    category: 'page-sections',
    subcategory: 'stats',
    tags: ['stats', 'stepped', 'cards', 'hierarchy'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/stats/Stepped.tsx'
  },
  {
    id: 'with-two-column-description-stats',
    name: 'With Two Column Description',
    description: 'Detailed description in two columns above statistics',
    category: 'page-sections',
    subcategory: 'stats',
    tags: ['stats', 'two-column', 'description', 'detailed'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/stats/WithTwoColumnDescription.tsx'
  },
  {
    id: 'with-description-stats',
    name: 'With Description',
    description: 'Side-by-side layout with mission description and large statistics',
    category: 'page-sections',
    subcategory: 'stats',
    tags: ['stats', 'side-by-side', 'mission', 'large'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/stats/WithDescription.tsx'
  },
  {
    id: 'simple-centered-testimonial',
    name: 'Simple Centered',
    description: 'Clean, centered testimonial layout with company logo, testimonial quote, and author information',
    category: 'page-sections',
    subcategory: 'testimonials',
    tags: ['testimonials', 'centered', 'simple', 'social-proof'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/testimonials/SimpleCentered.tsx'
  },
  {
    id: 'with-large-avatar-testimonial',
    name: 'With Large Avatar',
    description: 'A testimonial section featuring a large avatar image and detailed customer review',
    category: 'page-sections',
    subcategory: 'testimonials',
    tags: ['testimonials', 'avatar', 'large', 'social-proof'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/testimonials/WithLargeAvatar.tsx'
  },
  {
    id: 'with-overlapping-image-testimonial',
    name: 'With Overlapping Image',
    description: 'A testimonial layout with an overlapping profile image and quote marks design element',
    category: 'page-sections',
    subcategory: 'testimonials',
    tags: ['testimonials', 'overlapping', 'quote-marks', 'social-proof'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/testimonials/WithOverlappingImage.tsx'
  },
  {
    id: 'with-background-image-testimonial',
    name: 'With Background Image',
    description: 'A testimonial with a full background image, gradient overlays, and company logo',
    category: 'page-sections',
    subcategory: 'testimonials',
    tags: ['testimonials', 'background-image', 'gradient', 'social-proof'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/testimonials/WithBackgroundImage.tsx'
  },
  {
    id: 'side-by-side-testimonial',
    name: 'Side-by-side',
    description: 'Two testimonials displayed side-by-side with company logos and customer details',
    category: 'page-sections',
    subcategory: 'testimonials',
    tags: ['testimonials', 'side-by-side', 'logos', 'social-proof'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/testimonials/SideBySide.tsx'
  },
  {
    id: 'with-star-rating-testimonial',
    name: 'With Star Rating',
    description: 'A testimonial featuring a 5-star rating display using Heroicons star components',
    category: 'page-sections',
    subcategory: 'testimonials',
    tags: ['testimonials', 'star-rating', 'rating', 'social-proof'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/testimonials/WithStarRating.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'grid-testimonial',
    name: 'Grid',
    description: 'A complex masonry-style grid layout with a featured testimonial and multiple testimonial columns',
    category: 'page-sections',
    subcategory: 'testimonials',
    tags: ['testimonials', 'grid', 'masonry', 'social-proof'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/testimonials/Grid.tsx'
  },
  {
    id: 'subtle-grid-testimonial',
    name: 'Subtle Grid',
    description: 'A subtle column-based testimonials layout using CSS columns for natural flow',
    category: 'page-sections',
    subcategory: 'testimonials',
    tags: ['testimonials', 'subtle', 'columns', 'social-proof'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/testimonials/SubtleGrid.tsx'
  },
  {
    id: 'three-column-blog',
    name: 'Three Column',
    description: 'Standard three-column blog layout with titles, excerpts, author info, and category tags',
    category: 'page-sections',
    subcategory: 'blog-sections',
    tags: ['blog', 'three-column', 'grid', 'content'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/blog-sections/ThreeColumn.tsx'
  },
  {
    id: 'three-column-with-images-blog',
    name: 'Three Column With Images',
    description: 'Three-column blog layout with featured images for each article',
    category: 'page-sections',
    subcategory: 'blog-sections',
    tags: ['blog', 'three-column', 'images', 'featured'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/blog-sections/ThreeColumnWithImages.tsx'
  },
  {
    id: 'three-column-with-background-images-blog',
    name: 'Three Column With Background Images',
    description: 'Card-style layout with background images and overlay text for dramatic visual impact',
    category: 'page-sections',
    subcategory: 'blog-sections',
    tags: ['blog', 'background-images', 'cards', 'overlay'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/blog-sections/ThreeColumnWithBackgroundImages.tsx'
  },
  {
    id: 'single-column-blog',
    name: 'Single Column',
    description: 'Vertical single-column blog layout ideal for focused reading experience',
    category: 'page-sections',
    subcategory: 'blog-sections',
    tags: ['blog', 'single-column', 'vertical', 'minimal'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/blog-sections/SingleColumn.tsx'
  },
  {
    id: 'single-column-with-images-blog',
    name: 'Single Column With Images',
    description: 'Single-column layout with side-by-side images and content for rich visual storytelling',
    category: 'page-sections',
    subcategory: 'blog-sections',
    tags: ['blog', 'single-column', 'images', 'side-by-side'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/blog-sections/SingleColumnWithImages.tsx'
  },
  {
    id: 'with-featured-post-blog',
    name: 'With Featured Post',
    description: 'Two-column layout with a prominent featured post alongside a list of recent articles',
    category: 'page-sections',
    subcategory: 'blog-sections',
    tags: ['blog', 'featured', 'two-column', 'highlight'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/blog-sections/WithFeaturedPost.tsx'
  },
  {
    id: 'with-photo-and-list-blog',
    name: 'With Photo And List',
    description: 'Split layout combining a large photo with a structured list of job openings or opportunities',
    category: 'page-sections',
    subcategory: 'blog-sections',
    tags: ['careers', 'photo', 'list', 'jobs'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/blog-sections/WithPhotoAndList.tsx'
  },
  {
    id: 'contact-form-with-gradient',
    name: 'Contact Form With Gradient',
    description: 'Full contact form with gradient background, phone input with country selector, and privacy toggle',
    category: 'page-sections',
    subcategory: 'contact-sections',
    tags: ['contact', 'form', 'gradient', 'phone-input', 'privacy', 'sales', 'full-form'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/contact-sections/ContactFormWithGradient.tsx',
    dependencies: ['@heroicons/react/16/solid']
  },
  {
    id: 'side-by-side-grid',
    name: 'Side By Side Grid',
    description: 'Contact information and locations displayed in grid cards with dual sections',
    category: 'page-sections',
    subcategory: 'contact-sections',
    tags: ['contact', 'grid', 'locations', 'cards', 'contact-info', 'addresses', 'divided-sections'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/contact-sections/SideBySideGrid.tsx'
  },
  {
    id: 'split-with-pattern',
    name: 'Split With Pattern',
    description: 'Split layout with patterned background, contact info with icons, and contact form',
    category: 'page-sections',
    subcategory: 'contact-sections',
    tags: ['contact', 'split-layout', 'pattern', 'icons', 'form', 'contact-info', 'svg-pattern'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/contact-sections/SplitWithPattern.tsx',
    dependencies: ['@heroicons/react/24/outline']
  },
  {
    id: 'simple-four-column',
    name: 'Simple Four Column',
    description: 'Four-column office locations layout with left-aligned borders and address information',
    category: 'page-sections',
    subcategory: 'contact-sections',
    tags: ['contact', 'offices', 'locations', 'four-column', 'addresses', 'border-left'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/contact-sections/SimpleFourColumn.tsx'
  },
  {
    id: 'simple-centered',
    name: 'Simple Centered',
    description: 'Centered contact options with icons, support categories, and call-to-action links',
    category: 'page-sections',
    subcategory: 'contact-sections',
    tags: ['contact', 'centered', 'icons', 'support', 'sales', 'links', 'categories'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/contact-sections/SimpleCentered.tsx',
    dependencies: ['@heroicons/react/24/outline']
  },
  {
    id: 'with-testimonial',
    name: 'With Testimonial',
    description: 'Contact form with SVG pattern background, testimonial quote, and company logo',
    category: 'page-sections',
    subcategory: 'contact-sections',
    tags: ['contact', 'form', 'testimonial', 'pattern', 'logo', 'quote', 'backdrop-blur'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/contact-sections/WithTestimonial.tsx'
  },
  {
    id: 'split-with-image',
    name: 'Split With Image',
    description: 'Split layout with full-height image and comprehensive form with budget radio buttons',
    category: 'page-sections',
    subcategory: 'contact-sections',
    tags: ['contact', 'split-layout', 'image', 'form', 'radio-buttons', 'budget', 'comprehensive'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/contact-sections/SplitWithImage.tsx'
  },
  {
    id: 'team-with-small-images',
    name: 'With Small Images',
    description: 'Team section with small circular profile images and leadership focus',
    category: 'page-sections',
    subcategory: 'team-sections',
    tags: ['team', 'leadership', 'small-images', 'circular', 'grid'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/team-sections/WithSmallImages.tsx'
  },
  {
    id: 'team-with-large-images',
    name: 'With Large Images',
    description: 'Team section with large rectangular images and social media links',
    category: 'page-sections',
    subcategory: 'team-sections',
    tags: ['team', 'large-images', 'rectangular', 'social-links', 'three-column'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/team-sections/WithLargeImages.tsx'
  },
  {
    id: 'team-grid-with-round-images',
    name: 'Grid With Round Images',
    description: 'Compact team grid with round profile images for large teams',
    category: 'page-sections',
    subcategory: 'team-sections',
    tags: ['team', 'grid', 'round-images', 'compact', 'large-team', 'six-column'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/team-sections/GridWithRoundImages.tsx'
  },
  {
    id: 'team-large-grid-with-cards',
    name: 'Large Grid With Cards',
    description: 'Team section with large profile images in card format with social links',
    category: 'page-sections',
    subcategory: 'team-sections',
    tags: ['team', 'cards', 'large-images', 'social-links', 'centered', 'three-column'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/team-sections/LargeGridWithCards.tsx'
  },
  {
    id: 'team-with-image-and-paragraph',
    name: 'With Image And Paragraph',
    description: 'Team section with large images, detailed bio paragraphs, and social links',
    category: 'page-sections',
    subcategory: 'team-sections',
    tags: ['team', 'bio', 'paragraph', 'detailed', 'social-links', 'two-column'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/team-sections/WithImageAndParagraph.tsx'
  },
  {
    id: 'team-with-vertical-images',
    name: 'With Vertical Images',
    description: 'Team section with vertical 4:5 aspect ratio images and bio paragraphs in list format',
    category: 'page-sections',
    subcategory: 'team-sections',
    tags: ['team', 'vertical-images', 'bio', 'list-format', 'social-links', 'divided'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/team-sections/WithVerticalImages.tsx'
  },
  {
    id: 'team-full-width-with-vertical-images',
    name: 'Full Width With Vertical Images',
    description: 'Full width team grid with vertical images and bio descriptions in responsive layout',
    category: 'page-sections',
    subcategory: 'team-sections',
    tags: ['team', 'full-width', 'vertical-images', 'bio', 'responsive', 'grid'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/team-sections/FullWidthWithVerticalImages.tsx'
  },
  {
    id: 'team-grid-with-large-round-images',
    name: 'Grid With Large Round Images',
    description: 'Team grid with large circular profile images and social media links',
    category: 'page-sections',
    subcategory: 'team-sections',
    tags: ['team', 'large-round-images', 'circular', 'social-links', 'centered', 'three-column'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/team-sections/GridWithLargeRoundImages.tsx'
  },
  {
    id: 'team-with-medium-images',
    name: 'With Medium Images',
    description: 'Team grid with medium-sized rectangular images and location information',
    category: 'page-sections',
    subcategory: 'team-sections',
    tags: ['team', 'medium-images', 'rectangular', 'location', 'four-column', 'compact'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/team-sections/WithMediumImages.tsx'
  },
  {
    id: 'with-sticky-product-screenshot',
    name: 'With Sticky Product Screenshot',
    description: 'Complex content layout with sticky product screenshot and feature list',
    category: 'page-sections',
    subcategory: 'content-sections',
    tags: ['content', 'sticky', 'screenshot', 'features', 'icons', 'complex', 'two-column'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/content-sections/WithStickyProductScreenshot.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'with-testimonial',
    name: 'With Testimonial',
    description: 'Content section with testimonial sidebar and feature list with gradient background',
    category: 'page-sections',
    subcategory: 'content-sections',
    tags: ['content', 'testimonial', 'features', 'icons', 'gradient', 'two-column', 'sidebar'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/content-sections/WithTestimonial.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'with-image-titles',
    name: 'With Image Titles',
    description: 'About section with image grid, mission statement, and company statistics',
    category: 'page-sections',
    subcategory: 'content-sections',
    tags: ['content', 'about', 'images', 'grid', 'stats', 'mission', 'numbers'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/content-sections/WithImageTitles.tsx'
  },
  {
    id: 'two-columns-with-screenshot',
    name: 'Two Columns With Screenshot',
    description: 'Simple two-column content layout with large product screenshot',
    category: 'page-sections',
    subcategory: 'content-sections',
    tags: ['content', 'two-column', 'screenshot', 'cta', 'simple', 'product'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/content-sections/TwoColumnsWithScreenshot.tsx'
  },
  {
    id: 'with-testimonial-and-stats',
    name: 'With Testimonial And Stats',
    description: 'Company overview with testimonial card, mission statement, and key statistics',
    category: 'page-sections',
    subcategory: 'content-sections',
    tags: ['content', 'testimonial', 'stats', 'company', 'mission', 'about', 'card'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/content-sections/WithTestimonialAndStats.tsx'
  },
  {
    id: 'split-with-image',
    name: 'Split With Image',
    description: 'Split layout with full-height image and detailed content section with feature list',
    category: 'page-sections',
    subcategory: 'content-sections',
    tags: ['content', 'split', 'image', 'features', 'icons', 'full-height', 'workflow'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/content-sections/SplitWithImage.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'centered',
    name: 'Centered',
    description: 'Centered article-style content layout with testimonial quote and inline image',
    category: 'page-sections',
    subcategory: 'content-sections',
    tags: ['content', 'centered', 'article', 'testimonial', 'image', 'educational', 'blog'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/content-sections/Centered.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'simple-with-heading-logo-cloud',
    name: 'Simple with Heading',
    description: 'Logo cloud with centered heading and company logos in grid layout',
    category: 'page-sections',
    subcategory: 'logo-clouds',
    tags: ['logo-cloud', 'centered', 'heading', 'grid', 'trust-signals', 'companies'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/logo-clouds/SimpleWithHeading.tsx'
  },
  {
    id: 'simple-with-call-to-action-logo-cloud',
    name: 'Simple with Call-to-Action',
    description: 'Logo cloud with company logos and call-to-action link below',
    category: 'page-sections',
    subcategory: 'logo-clouds',
    tags: ['logo-cloud', 'cta', 'call-to-action', 'customer-stories', 'link', 'companies'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/logo-clouds/SimpleWithCallToAction.tsx'
  },
  {
    id: 'simple-left-aligned-logo-cloud',
    name: 'Simple Left-aligned',
    description: 'Left-aligned logo cloud with heading and company logos',
    category: 'page-sections',
    subcategory: 'logo-clouds',
    tags: ['logo-cloud', 'left-aligned', 'heading', 'grid', 'trust-signals', 'companies'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/logo-clouds/SimpleLeftAligned.tsx'
  },
  {
    id: 'split-with-logos-on-right-logo-cloud',
    name: 'Split with Logos on Right',
    description: 'Split layout with content on left and company logos grid on right',
    category: 'page-sections',
    subcategory: 'logo-clouds',
    tags: ['logo-cloud', 'split-layout', 'two-column', 'cta', 'content', 'companies', 'grid'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/logo-clouds/SplitWithLogosOnRight.tsx'
  },
  {
    id: 'simple-logo-cloud',
    name: 'Simple',
    description: 'Clean and minimal logo cloud with company logos in grid layout',
    category: 'page-sections',
    subcategory: 'logo-clouds',
    tags: ['logo-cloud', 'simple', 'minimal', 'grid', 'trust-signals', 'companies'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/logo-clouds/Simple.tsx'
  },
  {
    id: 'grid-logo-cloud',
    name: 'Grid',
    description: 'Logo cloud with company logos in bordered grid cells with background',
    category: 'page-sections',
    subcategory: 'logo-clouds',
    tags: ['logo-cloud', 'grid', 'bordered', 'cells', 'background', 'companies', 'rounded'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/logo-clouds/Grid.tsx'
  },
  {
    id: 'offset-with-supporting-text-faq',
    name: 'Offset With Supporting Text',
    description: 'FAQ section with offset layout and supporting text column',
    category: 'page-sections',
    subcategory: 'faqs',
    tags: ['faq', 'offset', 'supporting-text', 'two-column', 'customer-support', 'link'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/faqs/OffsetWithSupportingText.tsx'
  },
  {
    id: 'centered-accordion-faq',
    name: 'Centered Accordion',
    description: 'FAQ section with accordion functionality using Headless UI disclosure components',
    category: 'page-sections',
    subcategory: 'faqs',
    tags: ['faq', 'accordion', 'centered', 'disclosure', 'expandable', 'interactive'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/faqs/CenteredAccordion.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline']
  },
  {
    id: 'side-by-side-faq',
    name: 'Side-by-side',
    description: 'FAQ section with side-by-side layout on large screens, stacked on mobile',
    category: 'page-sections',
    subcategory: 'faqs',
    tags: ['faq', 'side-by-side', 'responsive', 'grid', 'question-answer', 'simple'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/faqs/SideBySide.tsx'
  },
  {
    id: 'three-columns-faq',
    name: 'Three Columns',
    description: 'FAQ section with three-column grid layout and supporting text',
    category: 'page-sections',
    subcategory: 'faqs',
    tags: ['faq', 'three-columns', 'grid', 'email-support', 'support-text', 'responsive'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/faqs/ThreeColumns.tsx'
  },
  {
    id: 'three-columns-centered-intro-faq',
    name: 'Three Columns With Centered Introduction',
    description: 'FAQ section with centered introduction and three-column grid layout',
    category: 'page-sections',
    subcategory: 'faqs',
    tags: ['faq', 'three-columns', 'centered-intro', 'grid', 'email-support', 'responsive'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/faqs/ThreeColumnsWithCenteredIntroduction.tsx'
  },
  {
    id: 'two-columns-faq',
    name: 'Two Columns',
    description: 'FAQ section with two-column grid layout and supporting text',
    category: 'page-sections',
    subcategory: 'faqs',
    tags: ['faq', 'two-columns', 'grid', 'email-support', 'support-text', 'responsive'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/faqs/TwoColumns.tsx'
  },
  {
    id: 'two-columns-centered-intro-faq',
    name: 'Two Columns With Centered Introduction',
    description: 'FAQ section with centered introduction and two-column grid layout',
    category: 'page-sections',
    subcategory: 'faqs',
    tags: ['faq', 'two-columns', 'centered-intro', 'grid', 'email-support', 'responsive'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/faqs/TwoColumnsWithCenteredIntroduction.tsx'
  },
  {
    id: 'four-column-with-company-mission',
    name: 'Four Column With Company Mission',
    description: 'Four-column footer with company logo, mission statement, and social links',
    category: 'page-sections',
    subcategory: 'footers',
    tags: ['footer', 'four-column', 'company-mission', 'social-links', 'logo', 'navigation'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/footers/FourColumnWithCompanyMission.tsx'
  },
  {
    id: 'four-column-with-call-to-action',
    name: 'Four Column With Call To Action',
    description: 'Four-column footer with prominent call-to-action section at top and navigation links below',
    category: 'page-sections',
    subcategory: 'footers',
    tags: ['footer', 'four-column', 'call-to-action', 'cta', 'navigation', 'social-links'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/footers/FourColumnWithCallToAction.tsx'
  },
  {
    id: 'four-column-simple',
    name: 'Four Column Simple',
    description: 'Clean four-column footer with logo and navigation links only',
    category: 'page-sections',
    subcategory: 'footers',
    tags: ['footer', 'four-column', 'simple', 'minimal', 'navigation', 'logo'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/footers/FourColumnSimple.tsx'
  },
  {
    id: 'four-column-with-newsletter',
    name: 'Four Column With Newsletter',
    description: 'Four-column footer with newsletter signup form and social media links',
    category: 'page-sections',
    subcategory: 'footers',
    tags: ['footer', 'four-column', 'newsletter', 'signup', 'email', 'social-links'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/footers/FourColumnWithNewsletter.tsx'
  },
  {
    id: 'four-column-with-newsletter-below',
    name: 'Four Column With Newsletter Below',
    description: 'Four-column footer with newsletter signup form positioned below navigation links',
    category: 'page-sections',
    subcategory: 'footers',
    tags: ['footer', 'four-column', 'newsletter', 'signup', 'email', 'social-links', 'below'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/footers/FourColumnWithNewsletterBelow.tsx'
  },
  {
    id: 'simple-centered',
    name: 'Simple Centered',
    description: 'Centered footer with navigation links, social icons, and copyright',
    category: 'page-sections',
    subcategory: 'footers',
    tags: ['footer', 'simple', 'centered', 'navigation', 'social-links', 'minimal'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/footers/SimpleCentered.tsx'
  },
  {
    id: 'simple-with-social-links',
    name: 'Simple With Social Links',
    description: 'Minimal footer with just social media icons and copyright text',
    category: 'page-sections',
    subcategory: 'footers',
    tags: ['footer', 'simple', 'minimal', 'social-links', 'copyright'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/footers/SimpleWithSocialLinks.tsx'
  },
  {
    id: 'with-stacked-flyout-menu',
    name: 'With Stacked Flyout Menu',
    description: 'Navigation header with stacked flyout menu and mobile support',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'flyout-menu', 'mobile-menu', 'stacked', 'products', 'popover'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/WithStackedFlyoutMenu.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline', '@heroicons/react/20/solid']
  },
  {
    id: 'constrained-header',
    name: 'Constrained',
    description: 'Simple constrained header with basic navigation and mobile menu',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'mobile-menu', 'simple', 'constrained', 'basic'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/Constrained.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline']
  },
  {
    id: 'on-brand-background-header',
    name: 'On Brand Background',
    description: 'Header with brand-colored background and white text elements',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'mobile-menu', 'brand-background', 'indigo', 'colored'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/OnBrandBackground.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline']
  },
  {
    id: 'with-full-width-flyout-menu',
    name: 'With Full Width Flyout Menu',
    description: 'Navigation header with full-width flyout menu spanning the viewport',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'flyout-menu', 'full-width', 'mobile-menu', 'products', 'grid', 'popover'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/WithFullWidthFlyoutMenu.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline', '@heroicons/react/20/solid']
  },
  {
    id: 'full-width-header',
    name: 'Full Width',
    description: 'Full-width header without max-width container constraints',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'mobile-menu', 'full-width', 'simple', 'unconstrained'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/FullWidth.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline']
  },
  {
    id: 'with-call-to-action-header',
    name: 'With Call To Action',
    description: 'Header with prominent call-to-action button alongside navigation',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'mobile-menu', 'cta', 'call-to-action', 'button', 'signup'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/WithCallToAction.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline']
  },
  {
    id: 'with-multiple-flyout-menus',
    name: 'With Multiple Flyout Menus',
    description: 'Header with multiple separate flyout menus for different navigation sections',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'multiple-flyouts', 'mobile-menu', 'products', 'company', 'dropdowns'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/WithMultipleFlyoutMenus.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline', '@heroicons/react/20/solid']
  },
  {
    id: 'with-icons-in-mobile-menu',
    name: 'With Icons In Mobile Menu',
    description: 'Header with icons displayed in mobile menu alongside text navigation',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'mobile-menu', 'icons', 'flyout-menu', 'sticky-cta', 'products'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/WithIconsInMobileMenu.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline', '@heroicons/react/20/solid']
  },
  {
    id: 'with-left-aligned-nav',
    name: 'With Left Aligned Nav',
    description: 'Header with navigation items aligned to the left alongside the logo',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'mobile-menu', 'left-aligned', 'simple', 'minimal'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/WithLeftAlignedNav.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline']
  },
  {
    id: 'with-right-aligned-nav',
    name: 'With Right Aligned Nav',
    description: 'Header with navigation items and login aligned to the right side',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'mobile-menu', 'right-aligned', 'simple', 'minimal', 'login'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/WithRightAlignedNav.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline']
  },
  {
    id: 'with-centered-logo',
    name: 'With Centered Logo',
    description: 'Header with centered logo and navigation split on both sides',
    category: 'elements',
    subcategory: 'headers',
    tags: ['header', 'navigation', 'mobile-menu', 'centered-logo', 'split-nav', 'balanced'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/headers/WithCenteredLogo.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline']
  },
  {
    id: 'stacked-with-footer-actions',
    name: 'Stacked with Footer Actions',
    description: 'Flyout menu with icons and footer action buttons for demo and sales',
    category: 'elements',
    subcategory: 'flyout-menus',
    tags: ['flyout', 'menu', 'dropdown', 'icons', 'actions', 'demo', 'sales', 'stacked'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/flyout-menus/StackedWithFooterActions.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'full-width-two-columns',
    name: 'Full-width Two-columns',
    description: 'Full-width flyout menu with two-column layout and recent posts section',
    category: 'elements',
    subcategory: 'flyout-menus',
    tags: ['flyout', 'menu', 'dropdown', 'full-width', 'two-columns', 'posts', 'blog', 'complex'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/flyout-menus/FullWidthTwoColumns.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'stacked-with-footer-list',
    name: 'Stacked with Footer List',
    description: 'Flyout menu with icons and footer list of recent posts',
    category: 'elements',
    subcategory: 'flyout-menus',
    tags: ['flyout', 'menu', 'dropdown', 'icons', 'footer-list', 'posts', 'resources', 'stacked'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/flyout-menus/StackedWithFooterList.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'full-width',
    name: 'Full-width',
    description: 'Full-width flyout menu with grid layout and footer action buttons',
    category: 'elements',
    subcategory: 'flyout-menus',
    tags: ['flyout', 'menu', 'dropdown', 'full-width', 'grid', 'actions', 'four-column'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/flyout-menus/FullWidth.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'simple-with-descriptions',
    name: 'Simple with Descriptions',
    description: 'Simple flyout menu with item descriptions but no icons',
    category: 'elements',
    subcategory: 'flyout-menus',
    tags: ['flyout', 'menu', 'dropdown', 'simple', 'descriptions', 'minimal', 'clean'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/flyout-menus/SimpleWithDescriptions.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid']
  },
  {
    id: 'two-column',
    name: 'Two-column',
    description: 'Two-column flyout menu with icons and enterprise promotion footer',
    category: 'elements',
    subcategory: 'flyout-menus',
    tags: ['flyout', 'menu', 'dropdown', 'two-column', 'icons', 'enterprise', 'grid'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/flyout-menus/TwoColumn.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'simple',
    name: 'Simple',
    description: 'Minimal flyout menu with text links only and no icons',
    category: 'elements',
    subcategory: 'flyout-menus',
    tags: ['flyout', 'menu', 'dropdown', 'simple', 'minimal', 'text-only', 'basic'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/elements/flyout-menus/Simple.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid']
  },

  // Banner Components
  {
    id: 'button-banner',
    name: 'Banner with Button',
    description: 'Notification banner with gradient background, message text, and call-to-action button',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'notification', 'button', 'cta', 'gradient', 'dismissible', 'announcement'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/ButtonBanner.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'dark-banner',
    name: 'Dark Banner',
    description: 'Simple dark banner with white text and dismiss button',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'notification', 'dark', 'simple', 'dismissible', 'announcement'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/DarkBanner.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'brand-banner',
    name: 'Brand Banner',
    description: 'Banner with brand color background and announcement text',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'notification', 'brand', 'indigo', 'dismissible', 'announcement'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/BrandBanner.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'background-glow-banner',
    name: 'Background Glow Banner',
    description: 'Banner with gradient background effects and glow elements',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'notification', 'gradient', 'glow', 'effects', 'dismissible', 'announcement'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/BackgroundGlowBanner.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'link-banner',
    name: 'Link Banner',
    description: 'Banner with inline text link and gradient background',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'notification', 'link', 'text-link', 'gradient', 'dismissible'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/LinkBanner.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'left-aligned-banner',
    name: 'Left Aligned Banner',
    description: 'Left-aligned banner with dark background and close button on right',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'notification', 'left-aligned', 'dark', 'dismissible', 'announcement'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/LeftAlignedBanner.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'bottom-aligned-banner',
    name: 'Bottom Aligned Banner',
    description: 'Fixed banner positioned at bottom of screen with full width',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'notification', 'bottom', 'fixed', 'full-width', 'dismissible', 'sticky'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/BottomAlignedBanner.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'floating-bottom-banner',
    name: 'Floating Bottom Banner',
    description: 'Floating banner positioned at bottom with rounded corners',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'notification', 'floating', 'bottom', 'rounded', 'dismissible', 'sticky'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/FloatingBottomBanner.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'floating-centered-banner',
    name: 'Floating Centered Banner',
    description: 'Centered floating banner at bottom with rounded design',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'notification', 'floating', 'centered', 'bottom', 'rounded', 'dismissible'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/FloatingCenteredBanner.tsx',
    dependencies: ['@heroicons/react/20/solid']
  },
  {
    id: 'privacy-right-aligned-banner',
    name: 'Privacy Notice Right Aligned',
    description: 'Cookie consent banner with right alignment and action buttons',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'privacy', 'cookie', 'consent', 'right-aligned', 'floating', 'gdpr'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/PrivacyRightAlignedBanner.tsx'
  },
  {
    id: 'privacy-centered-banner',
    name: 'Privacy Notice Centered',
    description: 'Cookie consent banner with centered layout and action buttons',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'privacy', 'cookie', 'consent', 'centered', 'floating', 'gdpr'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/PrivacyCenteredBanner.tsx'
  },
  {
    id: 'privacy-left-aligned-banner',
    name: 'Privacy Notice Left Aligned',
    description: 'Cookie consent banner with left alignment and action buttons',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'privacy', 'cookie', 'consent', 'left-aligned', 'floating', 'gdpr'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/PrivacyLeftAlignedBanner.tsx'
  },
  {
    id: 'privacy-full-width-banner',
    name: 'Privacy Notice Full Width',
    description: 'Full-width cookie consent banner with action buttons',
    category: 'elements',
    subcategory: 'banners',
    tags: ['banner', 'privacy', 'cookie', 'consent', 'full-width', 'bottom', 'gdpr'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/banners/PrivacyFullWidthBanner.tsx'
  },
  // 404 Pages
  {
    id: 'simple-404',
    name: 'Simple 404',
    description: 'Centered 404 page with minimal design and dual CTAs',
    category: 'application-ui',
    subcategory: '404-pages',
    tags: ['404', 'error', 'page-not-found', 'centered', 'simple', 'cta'],
    complexity: 'simple',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/404-pages/Simple404.tsx'
  },
  {
    id: 'split-with-404-image',
    name: 'Split with Image 404',
    description: 'Split layout 404 page with company logo, footer, and side image',
    category: 'application-ui',
    subcategory: '404-pages',
    tags: ['404', 'error', 'page-not-found', 'split', 'image', 'logo', 'footer'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/404-pages/SplitWith404Image.tsx'
  },
  {
    id: 'with-popular-pages-404',
    name: 'With Popular Pages 404',
    description: '404 page with popular pages list, company logo, and social links footer',
    category: 'application-ui',
    subcategory: '404-pages',
    tags: ['404', 'error', 'page-not-found', 'popular-pages', 'navigation', 'social-links', 'footer'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/404-pages/WithPopularPages404.tsx',
    dependencies: ['@heroicons/react/20/solid', '@heroicons/react/24/solid']
  },
  {
    id: 'with-background-image-404',
    name: 'With Background Image 404',
    description: 'Full-screen 404 page with background image and overlay text',
    category: 'application-ui',
    subcategory: '404-pages',
    tags: ['404', 'error', 'page-not-found', 'background-image', 'overlay', 'full-screen', 'centered'],
    complexity: 'medium',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/404-pages/WithBackgroundImage404.tsx'
  },
  {
    id: 'with-navbar-and-footer-404',
    name: 'With Navbar and Footer 404',
    description: 'Complete 404 page with full navigation header, mobile menu, and detailed footer',
    category: 'application-ui',
    subcategory: '404-pages',
    tags: ['404', 'error', 'page-not-found', 'navbar', 'footer', 'navigation', 'mobile-menu', 'complete'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/404-pages/WithNavbarAndFooter404.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/24/outline']
  },
  {
    id: 'complete-landing-page',
    name: 'Complete Landing Page',
    description: 'Full-featured landing page with hero, features, stats, CTA, and footer sections',
    category: 'page-examples',
    subcategory: 'landing-pages',
    tags: ['landing-page', 'complete', 'hero', 'features', 'stats', 'cta', 'footer', 'logo-cloud', 'testimonials', 'gradient', 'responsive', 'dark-mode', 'full-page'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/landing-pages/CompleteLandingPage.tsx',
    dependencies: ['@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'navigation-landing-page',
    name: 'Navigation Landing Page',
    description: 'Complete landing page with navigation, hero, features, testimonials, pricing, FAQs, and footer',
    category: 'page-examples',
    subcategory: 'landing-pages',
    tags: ['landing-page', 'navigation', 'complete', 'hero', 'features', 'testimonials', 'pricing', 'faqs', 'footer', 'mobile-menu', 'gradient', 'responsive', 'dark-mode', 'full-page'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/landing-pages/NavigationLandingPage.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'background-image-landing-page',
    name: 'Background Image Landing Page',
    description: 'Landing page with background image hero, collapsible FAQs, and side-by-side pricing',
    category: 'page-examples',
    subcategory: 'landing-pages',
    tags: ['landing-page', 'background-image', 'navigation', 'hero', 'features', 'testimonial', 'pricing', 'faq', 'collapsible', 'disclosure', 'footer', 'mobile-menu', 'gradient', 'responsive', 'dark-mode', 'full-page'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/landing-pages/BackgroundImageLandingPage.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'testimonials-landing-page',
    name: 'Testimonials Landing Page',
    description: 'Complete landing page with navigation, hero, testimonials grid, features, newsletter, and footer',
    category: 'page-examples',
    subcategory: 'landing-pages',
    tags: ['landing-page', 'testimonials', 'navigation', 'complete', 'hero', 'features', 'newsletter', 'footer', 'mobile-menu', 'gradient', 'responsive', 'dark-mode', 'full-page', 'logo-cloud', 'app-screenshot'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-sections/landing-pages/TestimonialsLandingPage.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'complete-with-faqs-pricing-page',
    name: 'Complete Pricing Page with FAQs',
    description: 'Complete pricing page with navigation, pricing tiers, logo cloud, testimonial, FAQs, and footer',
    category: 'page-examples',
    subcategory: 'pricing-pages',
    tags: ['pricing-page', 'complete', 'navigation', 'pricing', 'faqs', 'testimonial', 'logo-cloud', 'footer', 'mobile-menu', 'toggle', 'four-tier', 'responsive', 'dark-mode', 'full-page'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-examples/pricing-pages/CompleteWithFAQsPricingPage.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'comparison-table-pricing-page',
    name: 'Comparison Table Pricing Page',
    description: 'Advanced pricing page with detailed feature comparison table, dark header, and gradient backgrounds',
    category: 'page-examples',
    subcategory: 'pricing-pages',
    tags: ['pricing-page', 'comparison-table', 'feature-comparison', 'navigation', 'dark-header', 'gradient', 'three-tier', 'faqs', 'footer', 'mobile-responsive', 'social-links', 'responsive', 'dark-mode', 'full-page'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-examples/pricing-pages/ComparisonTablePricingPage.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  },
  {
    id: 'testimonials-with-newsletter-pricing-page',
    name: 'Testimonials with Newsletter Pricing Page',
    description: 'Clean pricing page with testimonials grid, newsletter signup, and minimal navigation',
    category: 'page-examples',
    subcategory: 'pricing-pages',
    tags: ['pricing-page', 'testimonials', 'newsletter', 'navigation', 'three-tier', 'clean-design', 'minimal', 'footer', 'social-links', 'responsive', 'dark-mode', 'full-page'],
    complexity: 'complex',
    responsive: true,
    darkMode: true,
    filePath: 'src/components/ui/page-examples/pricing-pages/TestimonialsWithNewsletterPricingPage.tsx',
    dependencies: ['@headlessui/react', '@heroicons/react/20/solid', '@heroicons/react/24/outline']
  }
  // More components will be added here as you import them from Tailwind UI Plus
];

// Helper functions for AI and developers
export function getComponentsByCategory(categoryId: string): ComponentInfo[] {
  return COMPONENT_REGISTRY.filter(component => component.category === categoryId);
}

export function getComponentsBySubcategory(subcategoryId: string): ComponentInfo[] {
  return COMPONENT_REGISTRY.filter(component => component.subcategory === subcategoryId);
}

export function searchComponents(query: string): ComponentInfo[] {
  const lowercaseQuery = query.toLowerCase();
  return COMPONENT_REGISTRY.filter(component =>
    component.name.toLowerCase().includes(lowercaseQuery) ||
    component.description.toLowerCase().includes(lowercaseQuery) ||
    component.tags.some(tag => tag.toLowerCase().includes(lowercaseQuery))
  );
}

export function getComponentById(id: string): ComponentInfo | undefined {
  return COMPONENT_REGISTRY.find(component => component.id === id);
}

// Update category counts dynamically
export function updateCategoryCounts(): ComponentCategory[] {
  return COMPONENT_CATEGORIES.map(category => ({
    ...category,
    subcategories: category.subcategories?.map(sub => ({
      ...sub,
      count: getComponentsBySubcategory(sub.id).length
    }))
  }));
}